type Style = Record<string, any>;

export const TEXT_TAGS: Record<string, Style> = {
  a: { color: 'blue', textDecorationLine: 'underline' },
  b: { fontWeight: 'bold' },
  strong: { fontWeight: 'bold' },
  em: { fontStyle: 'italic' },
  i: { fontStyle: 'italic' },
  u: { textDecorationLine: 'underline' },
  ins: { textDecorationLine: 'underline' },
  del: { textDecorationLine: 'line-through' },
  s: { textDecorationLine: 'line-through' },
  code: { fontFamily: 'Menlo' },
  kbd: { fontFamily: 'Menlo' },
  pre: { fontFamily: 'Menlo' },
  mark: { backgroundColor: 'yellow', color: 'black' },
  h1: { fontSize: 24, fontWeight: 'bold' },
  h2: { fontSize: 24, fontWeight: 'bold' },
  h3: { fontSize: 24, fontWeight: 'bold' },
  h4: { fontSize: 24, fontWeight: 'bold' },
  h5: { fontSize: 24, fontWeight: 'bold' },
  h6: { fontSize: 24, fontWeight: 'bold' },
  span: {},
  p: {},
  label: {},
  bdi: {},
  bdo: {},
  sub: {},
  sup: {},
  option: {},
  br: {},
};

export const VIEW_TAGS: Record<string, Style> = {
  div: {},
  article: {},
  aside: {},
  blockquote: {},
  fieldset: {},
  footer: {},
  form: {},
  header: {},
  main: {},
  nav: {},
  section: {},
  select: {},
  optgroup: {},
  ul: {},
  ol: {},
  li: {},
  button: { borderWidth: 1 },
  hr: { backgroundColor: 'black', height: 1, boxSizing: 'border-box' },
};
